import { BroadcastOrchestrator } from '@/services/broadcast/BroadcastOrchestrator';
import { BroadcastStore } from '@/services/broadcast/BroadcastStore';
import { EnrichmentCache } from '@/services/enrichment/EnrichmentCache';
import { Db } from '@/services/db/Db';
import type { LLMCaller, TTSCaller } from '@/services/broadcast/SegmentGenerator';
import type { ObjectStorage } from '@/services/storage/ObjectStorage';
import type { BackgroundEnricher } from '@/services/enrichment/BackgroundEnricher';
import type { FeatureFetchChain } from '@/services/broadcast/FeatureFetchChain';
import type { ManifestTrack, BroadcastCreateRequest } from '@/services/broadcast/types';
import { NEUTRAL_FEATURES } from '@/services/broadcast/audio-features';

function makeTracks(n: number): ManifestTrack[] {
  return Array.from({ length: n }, (_, i) => ({
    id: `t${i}`,
    title: `Track ${i}`,
    artistName: i % 2 === 0 ? 'Alpha' : 'Beta',
    albumTitle: 'Album',
    duration: 200 + i,
  }));
}

function makeOrch(db: Db) {
  const noopLLM: LLMCaller = { generate: async () => ({ text: 'commentary' }) };
  const noopTTS: TTSCaller = { synthesize: async () => ({ audioContent: 'AA==' }) };
  const noopStorage: ObjectStorage = { put: async (key) => `noop://${key}` };
  const enricher = { drainNow: async () => {} } as unknown as BackgroundEnricher;
  // DeterministicTrackSequencer requires fetchBatch to return an entry for every
  // track (tier-5 neutrals contract). An empty Map triggers a loud invariant
  // violation, so we return NEUTRAL_FEATURES for every track.
  const fetchChain = {
    fetchBatch: async (tracks: ManifestTrack[]) => {
      const out = new Map();
      for (const t of tracks) {
        out.set(t.id, { features: { ...NEUTRAL_FEATURES }, source: 'defaults', partial: false });
      }
      return out;
    },
  } as unknown as FeatureFetchChain;
  return new BroadcastOrchestrator(
    noopLLM, noopTTS, noopStorage,
    new BroadcastStore(db),
    new EnrichmentCache(db),
    enricher, fetchChain,
  );
}

const baseRequest: BroadcastCreateRequest & { userId: string } = {
  userId: 'u1',
  playlistId: 'p1',
  vibe: 'morning',
  length: 'quick',
  userContext: { timeOfDay: '09:00', dayOfWeek: 'Mon', firstTimeUser: false },
  tracks: makeTracks(8),
};

describe('generation invariant — sqlite store', () => {
  it('manifest track order is deterministic across two runs with the same id seed', async () => {
    // The seed is the broadcastId, which is generated by randomUUID() inside
    // create() — so we can't assert byte-for-byte equivalence without mocking
    // the UUID. Instead, assert the structural properties the migration
    // promised: same N tracks chosen, sparse cadence preserved, manifest JSON
    // returned by store.get() equals the one passed in (modulo slot status
    // overlays from broadcast_slots).
    const db = new Db(':memory:');
    const orch = makeOrch(db);
    const { manifest } = await orch.create(baseRequest);
    expect(manifest.tracks).toHaveLength(5); // quick = 5
    // Sparse cadence: cold_open + sign_off + transitions only before even-indexed tracks.
    const kinds = manifest.segmentSlots.map(s => s.kind);
    expect(kinds[0]).toBe('cold_open');
    expect(kinds[kinds.length - 1]).toBe('sign_off');
    // Wait for background slots to finish before closing the Db. Without this,
    // workers race the close and emit "database connection is not open" warnings.
    await orch.waitForCompletion(manifest.broadcastId);
    db.close();
  });

  it('store.get() round-trips the manifest with slot states overlaid', async () => {
    const db = new Db(':memory:');
    const orch = makeOrch(db);
    const { manifest } = await orch.create(baseRequest);
    const fetched = orch.getManifest(manifest.broadcastId)!;
    expect(fetched.broadcastId).toBe(manifest.broadcastId);
    expect(fetched.tracks).toEqual(manifest.tracks);
    expect(fetched.segmentSlots.length).toBe(manifest.segmentSlots.length);
    // Re-fetch after background work settles so slot 0's 'ready' status
    // isn't coupled to the synchronous slot-0 timing inside create().
    await orch.waitForCompletion(manifest.broadcastId);
    const settled = orch.getManifest(manifest.broadcastId)!;
    expect(settled.segmentSlots[0].status).toBe('ready');
    db.close();
  });
});
