#!/usr/bin/env bash
# scripts/env-dev.sh — auto-detect the laptop's LAN IP and write dev env config.
#
# Run from project root. Writes:
#   - .env.development   (root, read by Metro on `expo start`)
#   - server/.env        (BROADCAST_ASSET_BASE_URL patched in place — Node
#                         dotenv only reads .env, not .env.development)
#
# Metro/dotenv precedence: .env.development (dev builds) overrides .env (prod
# defaults). Production builds (EAS, Release) ignore .env.development entirely.

set -euo pipefail

# Try en0 (usually Wi-Fi on macOS), fall back to en1, then the first non-loopback.
detect_ip() {
  for iface in en0 en1; do
    local ip
    ip=$(ipconfig getifaddr "$iface" 2>/dev/null || true)
    if [[ -n "$ip" ]]; then
      echo "$ip"
      return 0
    fi
  done
  # Fallback: parse `ifconfig` for any non-loopback active IPv4.
  ifconfig 2>/dev/null \
    | awk '/inet / && $2 != "127.0.0.1" { print $2; exit }'
}

# macOS (BSD) sed takes `-i ''`; GNU sed takes `-i` alone. Detect which we have
# and stash the correct flag as an array so the call site can expand it safely.
if sed --version >/dev/null 2>&1; then
  # GNU sed — supports --version.
  SED_INPLACE=(-i)
else
  # BSD/macOS sed — requires an empty backup extension after -i.
  SED_INPLACE=(-i '')
fi

IP=$(detect_ip)

if [[ -z "$IP" ]]; then
  echo "env-dev: could not detect a LAN IP (no active en0/en1/non-loopback interface)" >&2
  exit 1
fi

ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)

# Root .env.development — Metro reads this on `expo start`.
cat > "${ROOT_DIR}/.env.development" <<EOF
# Auto-generated by scripts/env-dev.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# Overrides .env during dev. Do NOT commit — gitignored.
EXPO_PUBLIC_API_URL=http://${IP}:3001
EOF

# server/.env — patch BROADCAST_ASSET_BASE_URL in place. server/.env is
# local-dev only (prod runs on the VPS with its own .env), so clobbering this
# single line is safe. If the line is missing, append it.
SERVER_ENV="${ROOT_DIR}/server/.env"
server_patched=false
if [[ -f "$SERVER_ENV" ]]; then
  if grep -q '^BROADCAST_ASSET_BASE_URL=' "$SERVER_ENV"; then
    sed "${SED_INPLACE[@]}" \
      "s|^BROADCAST_ASSET_BASE_URL=.*|BROADCAST_ASSET_BASE_URL=http://${IP}:3001|" \
      "$SERVER_ENV"
  else
    echo "BROADCAST_ASSET_BASE_URL=http://${IP}:3001" >> "$SERVER_ENV"
  fi
  server_patched=true
else
  echo "env-dev: WARNING — server/.env not found; skipping server asset URL patch" >&2
fi

echo "env-dev: LAN IP ${IP}"
echo "  wrote .env.development"
if [[ "$server_patched" == true ]]; then
  echo "  patched server/.env BROADCAST_ASSET_BASE_URL"
fi
