#!/usr/bin/env bash
# scripts/env-dev.sh — auto-detect the laptop's LAN IP and write dev env files.
#
# Run from project root. Writes:
#   - .env.development             (root, read by Metro on `expo start`)
#   - server/.env.development      (server, read when NODE_ENV=development)
#
# Metro/dotenv precedence: .env.development (dev builds) overrides .env (prod).
# Production builds (EAS, `npx expo run:ios --configuration Release`) never see
# .env.development — they fall back to .env, which points at api.worthymedia.tech.

set -euo pipefail

# Try en0 (usually Wi-Fi on macOS), fall back to en1, then the first non-loopback.
detect_ip() {
  for iface in en0 en1; do
    local ip
    ip=$(ipconfig getifaddr "$iface" 2>/dev/null || true)
    if [[ -n "$ip" ]]; then
      echo "$ip"
      return 0
    fi
  done
  # Fallback: parse `ifconfig` for any non-loopback active IPv4.
  ifconfig 2>/dev/null \
    | awk '/inet / && $2 != "127.0.0.1" { print $2; exit }'
}

IP=$(detect_ip)

if [[ -z "$IP" ]]; then
  echo "env-dev: could not detect a LAN IP (no active en0/en1/non-loopback interface)" >&2
  exit 1
fi

ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)

# Root .env.development — Metro reads this on `expo start`.
cat > "${ROOT_DIR}/.env.development" <<EOF
# Auto-generated by scripts/env-dev.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# Overrides .env during dev. Do NOT commit — gitignored.
EXPO_PUBLIC_API_URL=http://${IP}:3001
EOF

# server/.env — Node dotenv only reads .env (not .env.development), so we
# patch the BROADCAST_ASSET_BASE_URL line in place. server/.env is local-dev
# only (prod runs on the VPS with its own .env), so this clobbering is safe.
# If the line is missing, append it.
SERVER_ENV="${ROOT_DIR}/server/.env"
if [[ -f "$SERVER_ENV" ]]; then
  if grep -q '^BROADCAST_ASSET_BASE_URL=' "$SERVER_ENV"; then
    sed -i '' "s|^BROADCAST_ASSET_BASE_URL=.*|BROADCAST_ASSET_BASE_URL=http://${IP}:3001|" "$SERVER_ENV"
  else
    echo "BROADCAST_ASSET_BASE_URL=http://${IP}:3001" >> "$SERVER_ENV"
  fi
else
  echo "env-dev: WARNING — server/.env not found; skipping server asset URL patch" >&2
fi

echo "env-dev: LAN IP ${IP}"
echo "  wrote .env.development"
echo "  patched server/.env BROADCAST_ASSET_BASE_URL"
